# Generated by Django 5.0.6 on 2024-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=260, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
