# Generated by Django 5.0.6 on 2024-05-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_user_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_address',
        ),
    ]
