# Generated by Django 5.0.6 on 2024-05-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
